# Generated by Django 5.1.4 on 2026-06-23 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral')], default='monthly', max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('target_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_deals', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_goals',
                'ordering': ['-year', '-month'],
                'unique_together': {('organization', 'user', 'period', 'year', 'month', 'quarter')},
            },
        ),
    ]
