# Generated by Django 6.0.6 on 2026-07-11 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('analytics', '0003_add_team_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgoal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamgoal',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
    ]
