# Generated by Django 6.0.6 on 2026-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_kbchunk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kbchunk',
            options={'ordering': ['section', 'chunk_index'], 'verbose_name': 'Fragmento KB', 'verbose_name_plural': 'Fragmentos KB'},
        ),
        migrations.AlterModelOptions(
            name='kbsource',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fuente de KB', 'verbose_name_plural': 'Fuentes de KB'},
        ),
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'verbose_name': 'Base de conocimiento', 'verbose_name_plural': 'Bases de conocimiento'},
        ),
        migrations.RemoveConstraint(
            model_name='kbchunk',
            name='unique_kb_chunk',
        ),
        migrations.AlterField(
            model_name='kbsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Importado el'),
        ),
        migrations.AlterUniqueTogether(
            name='kbchunk',
            unique_together={('knowledge_base', 'section', 'chunk_index')},
        ),
    ]
