# Generated by Django 5.1.4 on 2026-06-23 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('hero', 'Inicio — Hero & Características'), ('pricing', 'Precios'), ('features_page', 'Página de Características'), ('general', 'Configuración General')], max_length=50, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_content',
            },
        ),
    ]
