# Generated by Django 5.1.4 on 2026-06-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='key',
            field=models.CharField(choices=[('hero', 'Inicio — Hero & Características'), ('pricing', 'Precios'), ('features_page', 'Página de Características'), ('general', 'Configuración General'), ('nosotros', 'Nosotros'), ('contacto', 'Contacto'), ('privacidad', 'Política de Privacidad'), ('terminos', 'Términos y Condiciones')], max_length=50, unique=True),
        ),
    ]
