# Generated by Django 6.0.6 on 2026-06-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceplan',
            name='cta_text',
            field=models.CharField(default='Empezar prueba gratis', help_text='Texto del botón CTA en la tarjeta del plan', max_length=100),
        ),
        migrations.AlterField(
            model_name='voiceplan',
            name='features',
            field=models.JSONField(default=list, help_text='Array JSON de strings con las características del plan. Ej: ["1 agente de voz IA", "300 min/mes incluidos", "Soporte por chat"]'),
        ),
        migrations.AlterField(
            model_name='voiceplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Solo los planes activos se muestran en la landing'),
        ),
        migrations.AlterField(
            model_name='voiceplan',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Marca este plan como el más popular (resaltado visualmente)'),
        ),
        migrations.AlterField(
            model_name='voiceplan',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición (menor número = primero)'),
        ),
        migrations.AlterField(
            model_name='voicestat',
            name='label',
            field=models.CharField(help_text='Descripción de la métrica', max_length=200),
        ),
        migrations.AlterField(
            model_name='voicestat',
            name='value',
            field=models.CharField(help_text='Valor visible (ej. "24/7", "<1s", "+40%")', max_length=20),
        ),
    ]
