# Generated by Django 6.0.6 on 2026-06-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_plans', '0003_voicesetupplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicesetupplan',
            name='features',
            field=models.JSONField(default=list, help_text='Array JSON de objetos {text, highlight}. Ej: [{"text": "1 agente configurado", "highlight": false}, {"text": "Integración al CRM", "highlight": true}]'),
        ),
    ]
