# Generated by Django 5.1.4 on 2026-06-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='Descripción corta visible en la página de precios', max_length=255)),
                ('price_monthly', models.PositiveIntegerField(help_text='Precio mensual en centavos GTQ (ej. 19000 = Q190). Usa 0 para plan gratuito.')),
                ('price_annual', models.PositiveIntegerField(default=0, help_text='Precio anual en centavos GTQ (0 = sin modalidad anual)')),
                ('currency', models.CharField(default='GTQ', max_length=3)),
                ('cta_text', models.CharField(default='Empezar', max_length=100)),
                ('features', models.JSONField(default=list, help_text='Array de strings con las características incluidas, ej. ["Hasta 5 usuarios", "100 leads"]')),
                ('is_popular', models.BooleanField(default=False, help_text='Marca este plan como el más popular / recomendado')),
                ('is_active', models.BooleanField(default=True, help_text='Solo los planes activos se muestran en la página de precios y permiten checkout')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Orden en la página de precios (menor número = primero)')),
            ],
            options={
                'db_table': 'billing_plans',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(default='basico', help_text='Slug del plan activo (referencia a billing_plans.slug)', max_length=50),
        ),
    ]
