# Generated by Django 5.1.4 on 2026-06-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_add_plan_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_annual',
            field=models.PositiveIntegerField(default=0, help_text='Precio anual en centavos USD (0 = sin modalidad anual)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_monthly',
            field=models.PositiveIntegerField(help_text='Precio mensual en centavos USD (ej. 1900 = $19.00). Usa 0 para plan gratuito.'),
        ),
    ]
