# Generated by Django 5.1.4 on 2026-06-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_plan_currency_alter_plan_price_annual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price_annual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio anual en USD (ej. 190.00). Usa 0.00 si no hay modalidad anual.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, help_text='Precio mensual en USD (ej. 19.00). Usa 0.00 para plan gratuito.', max_digits=10),
        ),
    ]
