# Generated by Django 5.1.4 on 2026-06-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_price_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_trial',
            field=models.BooleanField(default=True, help_text='Ofrece período de prueba gratuita antes del primer cobro'),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Duración de la prueba gratuita en días (solo aplica si has_trial está activo)'),
        ),
    ]
