# Generated by Django 5.1.4 on 2026-06-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plan_trial_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Descripción breve visible en la página de precios')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en USD (ej. 8.00)', max_digits=10)),
                ('period', models.CharField(help_text='Texto del período (ej. /usuario/mes, pago único, /mes por bloque de +10 reglas)', max_length=100)),
                ('icon', models.CharField(choices=[('user-plus', 'Usuario adicional'), ('graduation-cap', 'Onboarding / formación'), ('workflow', 'Automatizaciones'), ('zap', 'Velocidad / rendimiento'), ('shield', 'Seguridad'), ('brain', 'Inteligencia artificial'), ('bar-chart-3', 'Analítica'), ('plug', 'Integraciones')], default='zap', help_text='Icono Lucide que se muestra en la tarjeta', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición (menor número = primero)')),
            ],
            options={
                'db_table': 'billing_addons',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(default=list, help_text='Array JSON de objetos con tres propiedades: "text" (nombre de la característica), "included" (true = incluida, false = bloqueada/gris), "highlight" (true = destacada en naranja, para diferenciadores clave del plan). Ej: [{"text": "2 usuarios incluidos", "included": true, "highlight": false}, {"text": "Lead Scoring IA", "included": false, "highlight": false}]'),
        ),
    ]
