# Generated by Django 5.1.4 on 2026-06-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_addon_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Destaca este add-on con borde naranja y badge en la página de precios', verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='description',
            field=models.TextField(help_text='Descripción breve visible en la página de precios', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='icon',
            field=models.CharField(choices=[('user-plus', 'Usuario adicional'), ('graduation-cap', 'Onboarding / formación'), ('workflow', 'Automatizaciones'), ('zap', 'Velocidad / rendimiento'), ('shield', 'Seguridad'), ('brain', 'Inteligencia artificial'), ('bar-chart-3', 'Analítica'), ('plug', 'Integraciones')], default='zap', help_text='Icono Lucide que se muestra en la tarjeta', max_length=50, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Solo los complementos activos se muestran en la página de precios y permiten checkout', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del complemento'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='period',
            field=models.CharField(help_text='Texto del período (ej. /usuario/mes, pago único, /mes por bloque de +10 reglas)', max_length=100, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio en USD (ej. 8.00)', max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug ó URL amigable'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición (menor número = primero)', verbose_name='Orden de aparición'),
        ),
    ]
