# Generated by Django 6.0.6 on 2026-06-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_addon_show_in_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Activo = permite checkout. Desactivado = no se puede contratar.', verbose_name='Activo'),
        ),
    ]
