# Generated by Django 6.0.6 on 2026-07-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_swap_automatizaciones_for_soporte_prioritario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='icon',
            field=models.CharField(choices=[('user-plus', 'Usuario adicional'), ('graduation-cap', 'Onboarding / formación'), ('workflow', 'Automatizaciones'), ('zap', 'Velocidad / rendimiento'), ('shield', 'Seguridad'), ('brain', 'Inteligencia artificial'), ('bar-chart-3', 'Analítica'), ('plug', 'Integraciones'), ('target', 'Estrategia / ventas')], default='zap', help_text='Icono Lucide que se muestra en la tarjeta', max_length=50, verbose_name='Icono'),
        ),
    ]
