# Generated by Django 6.0.6 on 2026-06-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embedform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Formulario incrustable', 'verbose_name_plural': 'Formularios incrustables'},
        ),
        migrations.AlterModelOptions(
            name='formsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Envío de formulario', 'verbose_name_plural': 'Envíos de formularios'},
        ),
        migrations.AlterField(
            model_name='embedform',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Si se rellena, redirige aquí tras el envío en lugar de mostrar el mensaje de éxito.', verbose_name='URL de redirección'),
        ),
        migrations.AlterField(
            model_name='embedform',
            name='style',
            field=models.JSONField(blank=True, default=dict, help_text='Ej: {"primary_color": "#ea580c", "bg_color": "#ffffff", "border_radius": "8"}', verbose_name='Estilo'),
        ),
    ]
