# Generated by Django 6.0.6 on 2026-07-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('basico', 'Básico'), ('pro', 'Professional'), ('equipo', 'Equipo'), ('enterprise', 'Enterprise')], default='free', max_length=50),
        ),
    ]
