# Generated by Django 5.1.4 on 2026-06-23 04:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('lead_created', 'Nuevo lead creado'), ('lead_score_high', 'Score de lead ≥ 80'), ('deal_won', 'Negocio ganado'), ('deal_lost', 'Negocio perdido'), ('task_overdue', 'Tarea vencida'), ('customer_at_risk', 'Cliente en riesgo de abandono')], max_length=50)),
                ('action_type', models.CharField(choices=[('send_whatsapp', 'Enviar mensaje de WhatsApp'), ('send_email', 'Enviar email'), ('create_task', 'Crear tarea'), ('notify_user', 'Notificar al usuario')], max_length=50)),
                ('action_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'automation_rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
