# Generated by Django 6.0.6 on 2026-07-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='action_type',
            field=models.CharField(choices=[('send_whatsapp', 'Enviar mensaje de WhatsApp'), ('send_email', 'Enviar email'), ('create_task', 'Crear tarea'), ('notify_user', 'Notificar al usuario'), ('assign_lead', 'Asignar lead automáticamente')], max_length=50),
        ),
    ]
