# Generated by Django 5.1.4 on 2026-06-23 02:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_type', models.CharField(choices=[('whatsapp', 'WhatsApp Business'), ('email', 'Email (SMTP/IMAP)'), ('outlook', 'Microsoft 365 / Outlook'), ('facebook', 'Facebook Pages'), ('instagram', 'Instagram Business'), ('telegram', 'Telegram'), ('sms', 'SMS / Twilio'), ('tiktok', 'TikTok Lead Generation'), ('google_calendar', 'Google Calendar'), ('automation_webhook', 'Automatización (Zapier · Make · n8n)'), ('ai_provider', 'Proveedor de IA')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connected', 'Conectado'), ('error', 'Error'), ('pending', 'Pendiente')], default='disconnected', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'integrations',
                'ordering': ['channel_type'],
                'unique_together': {('organization', 'channel_type')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente')], max_length=10)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('message_type', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integration')),
            ],
            options={
                'db_table': 'integration_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=500)),
                ('direction', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente')], default='inbound', max_length=10)),
                ('from_address', models.CharField(blank=True, max_length=500)),
                ('to_address', models.CharField(blank=True, max_length=500)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('thread_id', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integrations.integration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'inbox_messages',
                'ordering': ['-received_at'],
                'unique_together': {('integration', 'external_id')},
            },
        ),
    ]
