# Generated by Django 5.1.4 on 2026-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_webwidget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='channel_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp Business'), ('email', 'Email (SMTP/IMAP)'), ('brevo', 'Brevo (Email transaccional)'), ('outlook', 'Microsoft 365 / Outlook'), ('facebook', 'Facebook Pages'), ('instagram', 'Instagram Business'), ('telegram', 'Telegram'), ('sms', 'SMS / Twilio'), ('tiktok', 'TikTok Lead Generation'), ('google_calendar', 'Google Calendar'), ('automation_webhook', 'Automatización (Zapier · Make · n8n)'), ('ai_provider', 'Proveedor de IA')], max_length=50),
        ),
    ]
