# Generated by Django 5.1.4 on 2026-06-28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('crm', '0004_voice_agent_source_calendarevent_status'),
        ('integrations', '0003_add_brevo_channel'),
    ]

    operations = [
        # ── VoiceKnowledgeBase ────────────────────────────────────────────────
        migrations.CreateModel(
            name='VoiceKnowledgeBase',
            fields=[
                ('id',                      models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at',              models.DateTimeField(auto_now_add=True)),
                ('updated_at',              models.DateTimeField(auto_now=True)),
                ('company_info',            models.TextField(blank=True, help_text='Quiénes somos, misión, propuesta de valor', verbose_name='Sobre la empresa')),
                ('products_services',       models.TextField(blank=True, help_text='Qué ofrecemos, cómo funciona', verbose_name='Productos y servicios')),
                ('pricing',                 models.TextField(blank=True, help_text='Precios, planes, condiciones', verbose_name='Precios y planes')),
                ('faqs',                    models.TextField(blank=True, help_text='Q&A más comunes', verbose_name='Preguntas frecuentes')),
                ('working_hours',           models.CharField(blank=True, max_length=500, verbose_name='Horario de atención')),
                ('contact_info',            models.TextField(blank=True, help_text='Email, teléfono, ubicación, web', verbose_name='Información de contacto')),
                ('appointment_rules',       models.TextField(blank=True, help_text='Cómo agendar, disponibilidad, duración', verbose_name='Reglas de citas')),
                ('qualification_questions', models.JSONField(blank=True, default=list, help_text='Lista de strings. Ej: ["¿Cuántos empleados tiene?"]', verbose_name='Preguntas de calificación')),
                ('whatsapp_number',         models.CharField(blank=True, help_text='Con código de país, sin +. Ej: 50212345678', max_length=30, verbose_name='WhatsApp de escalado')),
                ('organization',            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'verbose_name':        'Base de conocimiento de voz',
                'verbose_name_plural': 'Bases de conocimiento de voz',
                'db_table':            'voice_knowledge_bases',
            },
        ),
        # ── VoiceWidget ───────────────────────────────────────────────────────
        migrations.CreateModel(
            name='VoiceWidget',
            fields=[
                ('id',                models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at',        models.DateTimeField(auto_now_add=True)),
                ('updated_at',        models.DateTimeField(auto_now=True)),
                ('token',             models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vapi_assistant_id', models.CharField(blank=True, max_length=100, verbose_name='Vapi Assistant ID')),
                ('knowledge_base',    models.OneToOneField(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='widget',
                    to='integrations.voiceknowledgebase',
                    verbose_name='Base de conocimiento',
                )),
                ('llm_model',         models.CharField(
                    choices=[
                        ('groq/llama-3.3-70b-versatile',       'Groq Llama 3.3 70B (recomendado)'),
                        ('groq/llama-3.1-8b-instant',           'Groq Llama 3.1 8B (ultra rápido)'),
                        ('openai/gpt-4o',                       'OpenAI GPT-4o'),
                        ('openai/gpt-4o-mini',                  'OpenAI GPT-4o Mini'),
                        ('anthropic/claude-3-5-haiku-20251001', 'Anthropic Claude 3.5 Haiku'),
                    ],
                    default='groq/llama-3.3-70b-versatile',
                    max_length=100,
                    verbose_name='Modelo LLM',
                )),
                ('is_active',         models.BooleanField(default=True, verbose_name='Activo')),
                ('lead_count',        models.PositiveIntegerField(default=0, verbose_name='Leads captados')),
                ('call_count',        models.PositiveIntegerField(default=0, verbose_name='Llamadas totales')),
                ('config',            models.JSONField(blank=True, default=dict)),
                ('organization',      models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'verbose_name':        'Widget de voz',
                'verbose_name_plural': 'Widgets de voz',
                'db_table':            'voice_widgets',
            },
        ),
        # ── VoiceCall ─────────────────────────────────────────────────────────
        migrations.CreateModel(
            name='VoiceCall',
            fields=[
                ('id',                 models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at',         models.DateTimeField(auto_now_add=True)),
                ('updated_at',         models.DateTimeField(auto_now=True)),
                ('widget',             models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='integrations.voicewidget', verbose_name='Widget')),
                ('vapi_call_id',       models.CharField(max_length=100, unique=True, verbose_name='Vapi Call ID')),
                ('caller_name',        models.CharField(blank=True, max_length=200)),
                ('caller_phone',       models.CharField(blank=True, max_length=30)),
                ('status',             models.CharField(
                    choices=[
                        ('completed',   'Completada'),
                        ('failed',      'Fallida'),
                        ('in_progress', 'En progreso'),
                    ],
                    default='in_progress',
                    max_length=30,
                    verbose_name='Estado',
                )),
                ('duration_seconds',   models.PositiveIntegerField(default=0, verbose_name='Duración (segundos)')),
                ('transcript',         models.TextField(blank=True, verbose_name='Transcript')),
                ('summary',            models.TextField(blank=True, verbose_name='Resumen')),
                ('sentiment',          models.CharField(blank=True, max_length=20, verbose_name='Sentimiento')),
                ('lead',               models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='crm.lead',
                    verbose_name='Lead',
                )),
                ('appointment',        models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='crm.calendarevent',
                    verbose_name='Cita',
                )),
                ('escalated_to_human', models.BooleanField(default=False, verbose_name='Escalado a humano')),
                ('qualification_data', models.JSONField(blank=True, default=dict, verbose_name='Datos de calificación')),
                ('ended_at',           models.DateTimeField(blank=True, null=True, verbose_name='Fin de llamada')),
                ('organization',       models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'verbose_name':        'Llamada de voz',
                'verbose_name_plural': 'Llamadas de voz',
                'db_table':            'voice_calls',
                'ordering':            ['-created_at'],
            },
        ),
    ]
