# Generated by Django 6.0.6 on 2026-06-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_voicewidget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicewidget',
            name='name',
            field=models.CharField(default='Agente de Voz', max_length=100, verbose_name='Nombre del agente'),
        ),
    ]
