# Generated by Django 6.0.6 on 2026-06-30 21:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('integrations', '0007_voicekbsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicekbsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # PostgreSQL cannot cast bigint → uuid directly.
        # Since the table is empty on a fresh database, we drop and recreate the PK column.
        migrations.RunSQL(
            sql=[
                "ALTER TABLE integrations_voicekbsource DROP COLUMN id;",
                "ALTER TABLE integrations_voicekbsource ADD COLUMN id uuid PRIMARY KEY DEFAULT gen_random_uuid();",
            ],
            reverse_sql=[
                "ALTER TABLE integrations_voicekbsource DROP COLUMN id;",
                "ALTER TABLE integrations_voicekbsource ADD COLUMN id bigserial PRIMARY KEY;",
            ],
        ),
        migrations.AlterField(
            model_name='voicekbsource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
    ]
