# Generated by Django 6.0.6 on 2026-07-03 04:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('integrations', '0012_voicecall_direction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='drivedocument',
            name='unique_drive_doc_per_entity',
        ),
        migrations.AddField(
            model_name='drivedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='googledrivetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        # PostgreSQL cannot cast bigint → uuid directly.
        # Since these tables are empty on a fresh database, we drop and recreate the PK columns.
        migrations.RunSQL(
            # drive_documents is the custom db_table set in DriveDocument.Meta
            sql=[
                "ALTER TABLE drive_documents DROP COLUMN id;",
                "ALTER TABLE drive_documents ADD COLUMN id uuid PRIMARY KEY DEFAULT gen_random_uuid();",
            ],
            reverse_sql=[
                "ALTER TABLE drive_documents DROP COLUMN id;",
                "ALTER TABLE drive_documents ADD COLUMN id bigserial PRIMARY KEY;",
            ],
        ),
        migrations.AlterField(
            model_name='drivedocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.RunSQL(
            # google_drive_tokens is the custom db_table set in GoogleDriveToken.Meta
            sql=[
                "ALTER TABLE google_drive_tokens DROP COLUMN id;",
                "ALTER TABLE google_drive_tokens ADD COLUMN id uuid PRIMARY KEY DEFAULT gen_random_uuid();",
            ],
            reverse_sql=[
                "ALTER TABLE google_drive_tokens DROP COLUMN id;",
                "ALTER TABLE google_drive_tokens ADD COLUMN id bigserial PRIMARY KEY;",
            ],
        ),
        migrations.AlterField(
            model_name='googledrivetoken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='drivedocument',
            unique_together={('organization', 'entity_type', 'entity_id', 'drive_file_id')},
        ),
    ]
