# Generated by Django 6.0.6 on 2026-07-11 02:49
# Patched: use SeparateDatabaseAndState so the DB is not touched if the
# column already has the correct type (avoids casting-integer-to-UUID failures
# on existing production rows).

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_remove_drivedocument_unique_drive_doc_per_entity_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # No DB operation — the column type is already correct in production
            # (or we are applying this for the first time to an empty table).
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='drivedocument',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='googledrivetoken',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='voicekbsource',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
