# Generated by Django 6.0.6 on 2026-07-11 02:49
# Patched: BigAutoField → UUID for google_drive_tokens and drive_documents
# using raw SQL (same technique as 0008 for voice_kb_sources) because
# PostgreSQL cannot cast bigint → uuid directly.
# voice_kb_sources already has UUID id (handled in 0008), so it's state-only.

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_remove_drivedocument_unique_drive_doc_per_entity_and_more'),
    ]

    operations = [
        # ── google_drive_tokens: bigint → uuid ────────────────────────────────
        migrations.RunSQL(
            sql=[
                "ALTER TABLE google_drive_tokens DROP COLUMN id;",
                "ALTER TABLE google_drive_tokens ADD COLUMN id uuid PRIMARY KEY DEFAULT gen_random_uuid();",
            ],
            reverse_sql=[
                "ALTER TABLE google_drive_tokens DROP COLUMN id;",
                "ALTER TABLE google_drive_tokens ADD COLUMN id bigserial PRIMARY KEY;",
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='googledrivetoken',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        # ── drive_documents: bigint → uuid ────────────────────────────────────
        migrations.RunSQL(
            sql=[
                "ALTER TABLE drive_documents DROP COLUMN id;",
                "ALTER TABLE drive_documents ADD COLUMN id uuid PRIMARY KEY DEFAULT gen_random_uuid();",
            ],
            reverse_sql=[
                "ALTER TABLE drive_documents DROP COLUMN id;",
                "ALTER TABLE drive_documents ADD COLUMN id bigserial PRIMARY KEY;",
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='drivedocument',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        # ── voice_kb_sources: already UUID since 0008, state update only ──────
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='voicekbsource',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
