# Generated by Django 6.0.6 on 2026-07-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_voicewidget_knowledge_base_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicewidget',
            name='knowledge_base_v2',
        ),
    ]
