# Generated by Django 6.0.6 on 2026-07-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_remove_voicewidget_knowledge_base_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='channel_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp Business'), ('email', 'Email (SMTP/IMAP)'), ('brevo', 'Brevo (Email transaccional)'), ('outlook', 'Microsoft 365 / Outlook'), ('facebook', 'Facebook Pages'), ('instagram', 'Instagram Business'), ('telegram', 'Telegram'), ('sms', 'SMS / Twilio'), ('tiktok', 'TikTok Lead Generation'), ('google_calendar', 'Google Calendar'), ('automation_webhook', 'Automatización (Zapier · Make · n8n)'), ('ai_provider', 'Proveedor de IA (legacy)'), ('ai_openai', 'OpenAI'), ('ai_groq', 'Groq'), ('ai_anthropic', 'Anthropic')], max_length=50),
        ),
    ]
