# Generated by Django 5.1.4 on 2026-08-24 03:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verification'),
        ('integrations', '0017_alter_integration_channel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utilidad'), ('AUTHENTICATION', 'Autenticación')], default='MARKETING', max_length=20)),
                ('language', models.CharField(default='es', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('paused', 'Pausado')], default='draft', max_length=20)),
                ('components', models.JSONField(blank=True, default=list)),
                ('meta_template_id', models.CharField(blank=True, max_length=100)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'whatsapp_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
