# Generated by Django 5.1.4 on 2026-06-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='sla_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Horas máximas de atención en esta etapa. Vacío = sin límite.', null=True),
        ),
    ]
