# Generated by Django 5.1.4 on 2026-06-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_pipeline_stage_sla_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email_opens',
            field=models.PositiveIntegerField(default=0, help_text='Número de veces que el lead abrió un email'),
        ),
        migrations.AddField(
            model_name='lead',
            name='link_clicks',
            field=models.PositiveIntegerField(default=0, help_text='Número de clics en enlaces enviados'),
        ),
        migrations.AddField(
            model_name='lead',
            name='page_visits',
            field=models.PositiveIntegerField(default=0, help_text='Número de visitas a páginas rastreadas'),
        ),
    ]
