# Generated by Django 5.1.4 on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_add_lead_engagement_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(
                choices=[
                    ('web',         'Sitio web'),
                    ('referral',    'Referido'),
                    ('cold_call',   'Llamada en frío'),
                    ('social',      'Redes sociales'),
                    ('event',       'Evento'),
                    ('voice_agent', 'Agente de voz'),
                    ('other',       'Otro'),
                ],
                default='web',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='status',
            field=models.CharField(
                choices=[
                    ('confirmed',            'Confirmada'),
                    ('pending_confirmation', 'Pendiente de confirmación'),
                    ('cancelled',            'Cancelada'),
                ],
                default='confirmed',
                max_length=30,
            ),
        ),
    ]
