# Generated by Django 6.0.6 on 2026-07-11 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('crm', '0007_lead_client_id_phone_required'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_organiz_943439_idx',
            old_name='leads_org_client_id_idx',
        ),
        migrations.AlterField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
