# Generated by Django 6.0.6 on 2026-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotwidget',
            options={'verbose_name': 'Widget de chatbot'},
        ),
        migrations.AlterField(
            model_name='chatbotwidget',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='chatbotwidget',
            name='llm_model',
            field=models.CharField(choices=[('groq/llama-3.3-70b-versatile', 'Groq Llama 3.3 70B (recomendado)'), ('groq/llama-3.1-8b-instant', 'Groq Llama 3.1 8B (ultra rápido)'), ('openai/gpt-4o-mini', 'OpenAI GPT-4o Mini'), ('openai/gpt-4o', 'OpenAI GPT-4o'), ('anthropic/claude-3-5-haiku-20251001', 'Anthropic Claude 3.5 Haiku')], default='groq/llama-3.3-70b-versatile', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatbotwidget',
            name='message_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Mensajes totales'),
        ),
        migrations.AlterField(
            model_name='chatbotwidget',
            name='name',
            field=models.CharField(default='Asistente', max_length=100, verbose_name='Nombre del chatbot'),
        ),
        migrations.AlterField(
            model_name='chatbotwidget',
            name='session_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Sesiones totales'),
        ),
        migrations.AlterField(
            model_name='chatbotwidget',
            name='system_prompt',
            field=models.TextField(blank=True, verbose_name='System prompt adicional'),
        ),
        migrations.AlterField(
            model_name='chatbotwidget',
            name='welcome_message',
            field=models.CharField(default='¡Hola! ¿En qué puedo ayudarte hoy?', max_length=500, verbose_name='Mensaje de bienvenida'),
        ),
    ]
