# Generated by Django 5.1.4 on 2026-07-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_capture_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='capture_state',
            field=models.CharField(choices=[('init', 'Inicio'), ('ask_id', 'Preguntando ID de referencia'), ('ask_name', 'Preguntando nombre'), ('ask_phone', 'Preguntando teléfono'), ('ask_email', 'Preguntando email'), ('ask_company', 'Preguntando empresa'), ('ask_killer', 'Pregunta de calificación'), ('active', 'Activo'), ('skip', 'Sin captura')], default='init', max_length=20),
        ),
    ]
